<a href="https://colab.research.google.com/github/NishmthaM/statistics_in_ml/blob/main/statistics_in_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# setting visual theme for seaborn

sns.set_theme(style="whitegrid")

1.loading dataset

In [3]:
#load tips dataset
df=sns.load_dataset("tips")

In [4]:
df.head() # for first 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df.tail() # to get last 5 rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

2.Measure of central tendency

In [7]:
print(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [8]:
col=df["total_bill"]

In [9]:
print(col)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [10]:
print(type(col))

<class 'pandas.core.series.Series'>

In [11]:
mean_value= col.mean()
print(mean_value)

19.78594262295082

In [12]:
mean_val = np.mean(col)
print(mean_val)

19.78594262295082

In [19]:
mean_val = np.mean(col)
meadian_val = np.median(col)
mode_val = col.mode()[0]
print(f"mean value is {mean_val:.2f}")
print(f"median value is {meadian_val:.1f}")
print(f"mode value is {mode_val:.0f}")

mean value is 19.79
median value is 17.8
mode value is 13